
#include "simple_system_common.h"

int main(int argc, char **argv) {

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");

  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_A, 0x3333);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OP_B, 0x4444);
  DEV_WRITE(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0x1);
  puthex(DEV_READ(POSIT_SINGLE_BASE + POSIT_SINGLE_OUTPUT, 0));
  puts("\n");
  

  return 0;
}
